### ISSUE TITLE
Test client doesn't attach user attribute to request

### ISSUE THREAD

**Issue by danielquinn** [Bouke/django-user-sessions#62]
I'm trying out the test client and my tests are exploding because I have signal handlers that listing for `user_logged_in()` and attempt to access `request.user`.  A brief stroll through the Django code for `login()` tells me that it won't attach `user` to the request unless the attribute is already set.

Given that the test client creates the request without attaching a `.user` attribute, this will never work as it is.  Could this be fixed by simply adding `request.user = None` right after [this line](https://github.com/Bouke/django-user-sessions/blob/master/user_sessions/utils/tests.py#L29)?

**Comment by Bouke** [comment]
I'm not that familiar with the test client, however I find it strange that `request.user` would not be available. It should be set by the [`AuthenticationMiddleware`][0]. Are you sure you've setup all middleware correctly?

[0]: https://github.com/django/django/blob/1.10.3/django/contrib/auth/middleware.py#L24

**Comment by danielquinn** [comment]
It does, but in a typical Django setup, `AuthenticationMiddleware` comes later in the stack than `SessionMiddleware`.  I agree that it's strange that `request.user` isn't available, but I'm just working with defaults here and the test client isn't working, hence this issue report :-(

**Comment by Bouke** [comment]
After snooping around in the code of Django's [`auth.login()`][0] code, I found what you're referring to: 

```
def login(request, user, backend=None):
    # ✁✁✁ snip ✁✁✁
    if hasattr(request, 'user'):
        request.user = user
    rotate_token(request)
    user_logged_in.send(sender=user.__class__, request=request, user=user)
```

So the signal `user_logged_in` will be passed the request that was passed to the `login` method. Since this package's (and also [upstream's][1]) test client doesn't set `request.user`, this property is also not available from your signal handler. The test client's `login` method doesn't use any middleware, so that's why `AuthenticationMiddleware` doesn't have any effect.

Could you test the fix that you propose in your initial comment? I think it should work fine.

[0]: https://github.com/django/django/blob/1.10.3/django/contrib/auth/__init__.py#L127-L130
[1]: https://github.com/django/django/blob/1.10.3/django/test/client.py#L638-L645

**Comment by danielquinn** [comment]
It does.  I just subclassed `user_sessions.utils.tests.Client` and overrided `login()` to change:

```python
request = HttpRequest()
```

to

```python
request = HttpRequest()
request.user = None
```

And everything works as expected.

Sorry, I'd submit a proper pull request, but I'm neck-deep in a legacy project I'm trying to bring up to speed, so this quick hack was all that I had time for. I just thought that upstream would like the heads-up.
